dict1={}
f1=input("Enter the name:")
n1=input("Enter the language:")
dict1.update({f1:n1})
f2=input("Enter the name:")
n2=input("Enter the language:")
dict1.update({f2:n2})
f3=input("Enter the name:")
n3=input("Enter the language:")
dict1.update({f3:n3})
f4=input("Enter the name:")
n4=input("Enter the language:")
dict1.update({f4:n4})
print(dict1)